# Default values for knative-serving.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  apiVersion: v1beta1

config:
  autoscaler:
    enableScaleToZero: "true"
    scaleToZeroThreshold: "5m"
  domain:
    default: ""

controller:
  replicaCount: 1
  image:
    repository: gcr.io/knative-releases/github.com/knative/serving/cmd/controller@sha256
    tag: 60b567eac333c20a86b52eb7b6de7f557e75abd41769530660ee7a03b03ece0c
    pullPolicy: IfNotPresent
  autoscaler:
    image:
      repository: gcr.io/knative-releases/github.com/knative/serving/cmd/autoscaler@sha256
      tag: 4439203216f64e89d5e9c6084307c8f22a6d50c47f9780b29cd9310decad580e
  queue:
    image:
      repository: gcr.io/knative-releases/github.com/knative/serving/cmd/queue@sha256
      tag: e844413efdf85deee7f7e677b2c267799a5385f92b61374cf74a48f3a278a789

autoscaler:
  replicaCount: 1
  image:
    repository: gcr.io/knative-releases/github.com/knative/serving/cmd/multitenant-autoscaler@sha256
    tag: a24e01989ceda0a6299f1595203433a9d99a4119bd9eb837d1af1edfabba9ab4
    pullPolicy: IfNotPresent

webhook:
  replicaCount: 1
  image:
    repository: gcr.io/knative-releases/github.com/knative/serving/cmd/webhook@sha256
    tag: 550594401aea26472a7dfc03b5ab957012c0057c28b1876bda85ec70fd2ffdaa
    pullPolicy: IfNotPresent

activator:
  replicaCount: 1
  image:
    repository: gcr.io/knative-releases/github.com/knative/serving/cmd/activator@sha256
    tag: 1b0d7f14e81fb15bb4f674e717e855b3fad476807f6e5e6a3cf0f8efcf1c1e05
    pullPolicy: IfNotPresent
