apiVersion: v1
kind: ConfigMap
metadata:
  name: config-controller
  labels:
    app: {{ template "knative-serving.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  # CONTROLLER CONFIGURATION

  # This is the Go import path for the binary that is containerized
  # and substituted here.
  queueSidecarImage: "{{ .Values.controller.queue.image.repository }}:{{ .Values.controller.queue.image.tag }}"

  # Comment the following lines to disable the single-tenant autoscaler.
  autoscalerImage: "{{ .Values.controller.autoscaler.image.repository }}:{{ .Values.controller.autoscaler.image.tag }}"

  # List of repositories for which tag to digest resolving should be skipped
  registriesSkippingTagResolving: "ko.local,dev.local"
