apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  labels:
    app: {{ template "knative-serving.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  # These are example settings of domain.
  # example.org will be used for routes having app=prod.
  # example.org: |
  #   selector:
  #     app: prod

  # Default value for domain, for routes that does not have app=prod labels.
  # Although it will match all routes, it is the least-specific rule so it
  # will only be used if no other domain matches.
  {{ default "example.com" .Values.config.domain.default }}: ""
