apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  labels:
    app: {{ template "knative-serving.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  concurrency-quantum-of-time: 100ms
  enable-scale-to-zero: "true"
  enable-vertical-pod-autoscaling: "false"
  max-scale-up-rate: "10"
  multi-concurrency-target: "1.0"
  panic-window: 6s
  scale-to-zero-threshold: 5m
  single-concurrency-target: "0.9"
  stable-window: 60s
  tick-interval: 2s
  vpa-multi-concurrency-target: "10.0"
