apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  labels:
    app: {{ template "knative-serving.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler
  labels:
    app: {{ template "knative-serving.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
