apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app: webhook
    chart: {{ template "knative-serving.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: webhook
    release: {{ .Release.Name }}
 