apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    app: controller-manager
    chart: {{ template "knative-eventing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.controllerManager.replicaCount }}
  selector:
    matchLabels:
      app: controller-manager
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: controller-manager
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: eventing-controller
      replicas: {{ .Values.controllerManager.replicaCount }}
      containers:
      - name: controller-manager
        image: "{{ .Values.controllerManager.image.repository }}:{{ .Values.controllerManager.image.tag }}"
        imagePullPolicy: {{ .Values.controllerManager.image.pullPolicy }}
        args:
        - -logtostderr
        - -stderrthreshold
        - INFO
