apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventing-controller
  labels:
    app: {{ template "knative-eventing.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterbus-controller
  labels:
    app: {{ template "knative-eventing.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
