apiVersion: v1
kind: Service
metadata:
  name: eventing-webhook
  labels:
    app: eventing-webhook
    role: eventing-webhook
    chart: {{ template "knative-eventing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: eventing-webhook
    release: {{ .Release.Name }}
