apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eventing-webhook
  labels:
    app: eventing-webhook
    chart: {{ template "knative-eventing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      app: eventing-webhook
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: eventing-webhook
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: eventing-controller
      containers:
      - name: eventing-webhook
        image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}"
        imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
