# Use --set or additional values.yaml file to configure settings.

# Common settings.
global:
  # Default repository for Istio images.
  # Releases are published to docker hub under 'istio' project.
  # Daily builds from prow are on gcr.io, and nightly builds from circle on
  # docker.io/istionightly
  hub: docker.io/istio

  # Default tag for Istio images.
  # Should track latest released version in the branch.
  tag: 1.0.0
  proxy:
  imagePullPolicy: IfNotPresent
  # controlPlaneMtls enabled. Will result in delays starting the pods while secrets are
  # propagated, not recommended for tests.
  controlPlaneSecurityEnabled: false

  # create RBAC resources. Must be set for any cluster configured with rbac.
  rbacEnabled: true

  # Specify pod scheduling arch(amd64, ppc64le, s390x) and weight as follows:
  #   0 - Never scheduled
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  arch:
    amd64: 2
    s390x: 2
    ppc64le: 2

#
# knative ingressgateway configuration
#
knative:
  ingressgateway:
    enabled: true
    serviceAccountName: istio-ingressgateway-service-account
    autoscaleMin: 1
    autoscaleMax: 10
    replicaCount: 1
    resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
    service:
      loadBalancerIP: ""
      type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    deployment:
      secretVolumes:
      - name: ingressgateway-certs
        secretName: istio-ingressgateway-certs
        mountPath: /etc/istio/ingressgateway-certs
