# Based on: istio/charts/ingressgateway/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: knative-ingressgateway
  labels:
    app: knative-ingressgateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    knative: ingressgateway
spec:
  replicas: {{ .Values.knative.ingressgateway.replicaCount }}
  template:
    metadata:
      labels:
        knative: ingressgateway
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Values.knative.ingressgateway.serviceAccountName }}
      containers:
        - name: {{ template "knative-istio.name" . }}
          image: "{{ .Values.global.hub }}/proxyv2:{{ .Values.global.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 32400
          args:
          - proxy
          - router
          - -v
          - "2"
          - --discoveryRefreshDelay
          - '1s' #discoveryRefreshDelay
          - --drainDuration
          - '45s' #drainDuration
          - --parentShutdownDuration
          - '1m0s' #parentShutdownDuration
          - --connectTimeout
          - '10s' #connectTimeout
          - --serviceCluster
          - knative-ingressgateway
          - --zipkinAddress
          - zipkin:9411
          - --statsdUdpAddress
          - istio-statsd-prom-bridge:9125
          - --proxyAdminPort
          - "15000"
        {{- if .Values.global.controlPlaneSecurityEnabled }}
          - --controlPlaneAuthPolicy
          - MUTUAL_TLS
          - --discoveryAddress
          - istio-pilot:15005
        {{- else }}
          - --controlPlaneAuthPolicy
          - NONE
          - --discoveryAddress
          - istio-pilot:8080
        {{- end }}
          resources:
            {}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          volumeMounts:
          - name: istio-certs
            mountPath: /etc/certs
            readOnly: true
          {{- range .Values.knative.ingressgateway.deployment.secretVolumes }}
          - name: {{.name }}
            mountPath: {{.mountPath | quote}}
            readOnly: true
          {{- end }}
      volumes:
      - name: istio-certs
        secret:
          secretName: "istio.default"
          optional: true
      {{- range .Values.knative.ingressgateway.deployment.secretVolumes }}
      - name: {{.name }}
        secret:
          secretName: {{.secretName | quote}}
          optional: true
      {{- end }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
